# Generated by Django 2.1.1 on 2018-11-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=30)),
                ('poNumber', models.CharField(max_length=30)),
                ('deliveryLoc', models.TextField()),
                ('shipVia', models.CharField(max_length=10)),
                ('tId', models.IntegerField()),
                ('description', models.TextField()),
                ('container', models.CharField(max_length=30)),
                ('carrier', models.CharField(max_length=30)),
                ('trackingNo', models.CharField(max_length=30)),
                ('qtyShipped', models.IntegerField()),
                ('shipInvoiceDate', models.DateTimeField()),
            ],
        ),
    ]
